### ISSUE TITLE
横引き出し気になった点（車）

### ISSUE THREAD

**Issue by kuruma-gs** [sikmi/webweb#307]
1. タイトル名をクリックすると別サイトに遷移する（普通タイトルクリックしますよね）

2. スクロールが2重になる
JSでマウス位置などをとって制御するとか？

3. iframe重い
重いので、ローダーをせめてつける
やたら重いのはなんとかなるんだろうか？

4. 今見ているものが一覧でも分かると良い（任意）
今見ているものを色をかえるなり、ハイライト線を追加するなりすると良いかな

5. 行のマウスオーバーの色
グレーはどちらかといえば非活性を連想させるため、クリックできる感がある色に変更してほしい（PorductHuntは黄色でした）

6. 画像のインタラクション
何も動きがないのでほしいところ

7. サービスじゃない部分をクリックした時も閉じて欲しい
ただ、画像などをクリックしたら今の動きが良い

**Comment by Hozum** [comment]
> タイトル名をクリックすると別サイトに遷移する（普通タイトルクリックしますよね）
タイトルを押しても公式サイトに遷移しないようにし、別途公式サイトへのリンク作ります。

> スクロールが2重になる
スクロールが2重になるものと、ならないものがあるみたいなので、原因調査します。

> iframe重い
重いですね。代用品がないか探します。
なかったら、Loading つけます。

> 今見ているものが一覧でも分かると良い（任意）
了解です。

> 行のマウスオーバーの色
わかりました。

> 画像のインタラクション
復帰させます。

**Comment by kuruma-gs** [comment]
@Hozum スクロールが2重になるのは、iframeでのスクロールが終わった後っぽいですね。下まで行くと本体の方がうごきます。

**Comment by Hozum** [comment]
@kuruma3 なるほど。iframe のスクロールが完了した後は、本体の方は動かないほうがいいですね。対応します。
