### ISSUE TITLE
横引き出しで気になった点

### ISSUE THREAD

**Issue by kamomc** [sikmi/webweb#308]
- ドロアを閉じるために左上にカーソルを持っていくのが面倒。
 - 引き出し外領域をクリックしたら閉じるでもいいかも。
- 左上の閉じるボタンはすぐに表示されてほしい。
- 引き出しが出切るまで前の内容が表示されたままなのが違和感。
- 引用元をもうちょい目立たせたい。（引用元への敬意）
- スマホだとレイアウトが崩れる
- スマホだとiframeがスクロールできない

**Comment by Hozum** [comment]
> ドロアを閉じるために左上にカーソルを持っていくのが面倒。
> 引き出し外領域をクリックしたら閉じるでもいいかも。

ドロアを表示したまま、他のサービスを選択できるようになっているので、
画面外クリックで閉じるのはしたくないな。

> 左上の閉じるボタンはすぐに表示されてほしい。

了解です。

> 引き出しが出切るまで前の内容が表示されたままなのが違和感。

確かにｗ　一旦クリアします。

> 引用元をもうちょい目立たせたい。（引用元への敬意）

サービス名を入れる + もう少し大きくしてみる

> スマホだとレイアウトが崩れる

対応します。

> スマホだとiframeがスクロールできない

本当だ....何とかします。

**Comment by kuruma-gs** [comment]
@Hozum @kamomc 
> ドロアを表示したまま、他のサービスを選択できるようになっているので、
画面外クリックで閉じるのはしたくないな。

は、画像などサービスをクリックした時は今の動きでそれ以外をクリックしたら閉じる動きだと使っていて自然に感じました。

**Comment by Hozum** [comment]
@kuruma3 そうします。

**Comment by Hozum** [comment]
> 引用元をもうちょい目立たせたい。（引用元への敬意）
やっぱりサービス名を入れるのは辞めます。サイトを見ればわかるので。
