### ISSUE TITLE
【view】Social系の導入

### ISSUE THREAD

**Issue by kuruma-gs** [sikmi/webweb#32]
① OGP
　Google+, facebook, gree, mixi が対応
② Twitter Card
③ microdata
　Google+ 用の記述（ogpがあれが十分の模様）
④ はてぶ対策
⑤ 他のSNSで何か設定すべきものがあるか調査

**Comment by kamomc** [comment]
メモ書き。実装の際に参考にする。

① OGP
　メタタグを４行程度書追加する。
　公式: http://ogp.me/
　日本語解説: http://nex.fm/ogp/

② Twitter Card
　写真や動画などのリッチメディアをツイートに添付できる。
　メタタグを６行程度追加する。
　公式: https://dev.twitter.com/ja/cards/overview

③ microdata
　body内にタグを追加。
　Google+はOGPも有効だが、こちらが優先される。
　https://developers.google.com/+/web/snippet/?hl=ja

④ はてぶ対策
　新着エントリーに載らねばランキング入りは無い
　　→ 最初にブックマークされてから一定時間以内に３ブックマークされた場合新着に載る(一定時間: 12hという説あり。)
　　→ 毎回同アカウントだとスパムとして認識される恐れあり。

⑤ 他のSNSで何か設定すべきものがあるか調査
  ※ 対象とするSNS
　　SNS利用率ランキング BEST 6を対象とする。（データ: http://www.ictr.co.jp/report/20140821000067.html)

1. LINE -> 未対応
2. Twitter -> Twitterカードで対応
3. Facebook -> OGPで対応
4. mixi -> OGPで対応
5. Skype -> 未対応
6. Google+ -> microdata & OGPで対応

LINE および Skype について対策を打つ必要があるのか、要検討。

**Comment by kamomc** [comment]
LINE と Skype の活用について調査してみた。

1. LINE
　LINE@という広報アカウント提供サービスあり。
　→ 実店舗を持たない企業は登録不可。
　公式: http://at.line.me/jp/

2. Skype
　webweb普及には使えなさそう。
