### ISSUE TITLE
【view】Google ad 導入

### ISSUE THREAD

**Issue by Hozum** [sikmi/webweb#63]

**Comment by kamomc** [comment]
■ 広告を作成する際に必要情報
　1. 広告の名称
　　→ 命名規則を相談しておきたい。後の分析のしやすさを左右するため。
　　　※ 相談事項1
　2. 広告サイズ
　　→ 複数パターンから選択可。ただし、サイズは固定。
　　　※ 相談事項2, 3
　3. 広告タイプ
　　→ テキスト広告 or ディスプレイ広告 or 両方 から選択可。
　　　特にこだわりがなければ両方にしておきます。
　4. 広告のスタイル
　　→ コンテンツと統一感があるとクリック率が上がる。
　　　作業時にいい感じにしておきます。
　5. カスタムチャネル
　　→ 表示させる広告を指定することができる。特に設定の必要はない。
　　　未設定時はユーザの過去の検索履歴等から適切な広告を選択してくれる。
　6. 代替広告
　　→ 広告はタグを書いてから表示されるまでに時間がかかるので、その間に表示させる広告。
　　　(1)空白スペース
　　　(2)他のURLの別広告
　　　(3)無地一色で塗りつぶす
　　　から選択可。特に要望がなければ(2)にします。

■ 相談事項
　1. 広告の名称の命名規則
　　[サービス名]_[ページ名]_[広告タイプ]_[表示位置]_[連番] がいいかな。
　　例: WebxWebのトップページのサイドメニューの広告の場合
　　webweb_top_lectl_sidemenu_0
　　webweb_top_lectl_sidemenu_1
　　注) lectl -> レクタングル(大)

　2. 広告のサイズ
　　画面モックの広告サイズは 319x150 になっているが、そのサイズの広告は存在しない。
　　枠に入るやつでいい感じのサイズは 336x280 だけど、それでいいですか？

　3. モバイル対応ってどうなっているのか？
　　共通にする場合はモバイル推奨サイズの広告を使う必要がある。なお、上述した 336x280 は非対応。

**Comment by kamomc** [comment]
#71 が終わり次第、広告を会社アカウントのものに切り替える。

**Comment by yuutabuchi** [comment]
広告ユニット作成しました。これ穂積君対応できる？
ユニット名: webweb_top_lect_sidemenu_1
コード: 
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>

<ins class="adsbygoogle"
     style="display:inline-block;width:300px;height:250px"
     data-ad-client="ca-pub-2139439104865613"
     data-ad-slot="7261260086"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>

**Comment by Hozum** [comment]
対応できます。
広告枠３つ欲しいのですが、slot 増やせますか？

**Comment by yuutabuchi** [comment]
ユニット名: webweb_top_lect_sidemenu_2
コード: 
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>

<ins class="adsbygoogle"
     style="display:inline-block;width:300px;height:250px"
     data-ad-client="ca-pub-2139439104865613"
     data-ad-slot="2074180883"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>

**Comment by yuutabuchi** [comment]
webweb_top_lect_sidemenu_3

<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>

<ins class="adsbygoogle"
     style="display:inline-block;width:300px;height:250px"
     data-ad-client="ca-pub-2139439104865613"
     data-ad-slot="3550914085"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
